export const ADD_TO_CART = "ADD_TO_CART";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

