export const GET_PRODUCTLIST_REQUEST = "GET_PRODUCTLIST_REQUEST";
export const GET_PRODUCTLIST_SUCCESS = "GET_PRODUCTLIST_SUCCESS";
export const GET_PRODUCTLIST_FAIL = "GET_PRODUCTLIST_FAIL";

export const GET_PRODUCTDETAIL_REQUEST = "GET_PRODUCTDETAIL_REQUEST";
export const GET_PRODUCTDETAIL_SUCCESS = "GET_PRODUCTDETAIL_SUCCESS";
export const GET_PRODUCTDETAIL_FAIL = "GET_PRODUCTDETAIL_FAIL";

export const ADD_TO_RECENT_VIEW = "ADD_TO_RECENT_VIEW";
