export const GET_SIGNIN_REQUEST = "GET_SIGNIN_REQUEST";
export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";
export const GET_SIGNIN_FAIL = "GET_SIGNIN_FAIL";
export const GET_SIGNOUT = "GET_SIGNOUT";

export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_FAIL = "GET_REGISTER_FAIL";